In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [57]:
#dataset = pd.read_csv('C:/Users/SRTINNI/Desktop/covid_lstm.csv',index_col='Date',parse_dates=True)
#dataset.index.asfreq = 'MS'
##dataset.shape

#dataset = pd.read_csv('C:/Users/SRTINNI/Desktop/TPW/Datasets/covid-19 data set/this dataset are final/covid_full.csv',index_col='DATE'   ,parse_dates=True)
#dataset = pd.read_csv('C:/Users/SRTINNI/Desktop/TPW/Datasets/covid-19 data set/this dataset are final/covid_full.csv')

#dataset=dataset.dropna()
#dataset.columns
#dataset

In [58]:
import datetime as dt

In [59]:
import numpy as np


In [60]:
#dataset = pd.read_csv('C:/Users/SRTINNI/Desktop/covid_lstm.csv')
dataset = pd.read_csv('C:/Users/SRTINNI/Desktop/TPW/Datasets/covid-19 data set/this dataset are final/covid_full.csv')
dataset.index.asfreq = 'MS'
dataset=dataset.dropna()
dataset.head()
#dataset.dtypes

DATE  total_cases  Daily new cases  new_cases_smoothed  total_deaths  \
35  07-04-20        164.0             41.0              16.143          17.0   
36  08-04-20        218.0             54.0              23.429          20.0   
37  09-04-20        330.0            112.0              39.143          21.0   
38  10-04-20        424.0             94.0              51.857          27.0   
39  11-04-20        482.0             58.0              58.857          30.0   

    new_deaths  new_deaths_smoothed  total_cases_per_million  \
35         5.0                1.714                    0.986   
36         3.0                2.000                    1.311   
37         1.0                2.143                    1.984   
38         6.0                3.000                    2.550   
39         3.0                3.143                    2.898   

    new_cases_per_million  new_cases_smoothed_per_million  \
35                  0.247                           0.097   
36                  0.325                           0.141   
37                  0.673                           0.235   
38                  0.565                           0.312   
39                  0.349                           0.354   

    total_deaths_per_million  new_deaths_per_million  \
35                     0.102                   0.030   
36                     0.120                   0.018   
37                     0.126                   0.006   
38                     0.162                   0.036   
39                     0.180                   0.018   

    new_deaths_smoothed_per_million  reproduction_rate  
35                            0.010               2.73  
36                            0.012               2.78  
37                            0.013               2.82  
38                            0.018               2.71  
39                            0.019               2.60

In [61]:
dataset.dtypes

DATE                                object
total_cases                        float64
Daily new cases                    float64
new_cases_smoothed                 float64
total_deaths                       float64
new_deaths                         float64
new_deaths_smoothed                float64
total_cases_per_million            float64
new_cases_per_million              float64
new_cases_smoothed_per_million     float64
total_deaths_per_million           float64
new_deaths_per_million             float64
new_deaths_smoothed_per_million    float64
reproduction_rate                  float64
dtype: object

In [62]:
#dataset['Date1']=pd.to_datetime(dataset.Date)

In [63]:
X=np.array(dataset[['total_cases','new_deaths','total_cases_per_million','new_cases_per_million','total_deaths','new_deaths_per_million']])
X.shape

(625, 6)

In [64]:
y= np.array(dataset['Daily new cases'])
y.shape

(625,)

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30)
#X_train.shape
X_test.shape

(188, 6)

In [66]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\SRTINNI\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.0

In [67]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.0

In [68]:
lir = LinearRegression()
lir.fit(X_train, y_train)
lir.score(X_test, y_test)

0.9999999996691239

In [69]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.005319148936170213

In [70]:
#folding on train dataset
from sklearn.model_selection import cross_val_score
#10 fold cv
scores = cross_val_score(lir,X_train,y_train,scoring='r2',cv=10)
scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
print(np.mean(scores))

0.9999999997352319


In [72]:
#printing the scores on the test dataset
# First prediction
from sklearn.model_selection import cross_val_predict
#the prediction
pred = cross_val_predict(lir,X_test,y_test)
pred

array([ 1607.98565651,  2518.99819406,  8660.92285681,  3199.999108  ,
        7614.04293543,  1487.91871472,  1540.96628682,   978.02754175,
         472.96437845,  2694.9493832 ,  3724.02399924,  1334.91642387,
        2735.02613637,  1140.0064106 ,  3489.03377287,  5726.98276744,
        6028.00841966,   606.00721461,  2685.95888612,   644.89810886,
        3480.06011058,   293.00637351,  3435.98292654,  1873.06364683,
         305.98931102,  1382.95759748,   599.00608315,  2587.99688979,
        1950.07969778,  2595.00574731,  7625.99948934,  1702.942288  ,
        5249.0356909 ,  1592.0152656 ,  2960.03359506,   844.98441317,
        3736.99823029,  3034.0349721 ,  1382.97943135,  1970.03171774,
        2906.9741447 ,  1681.9967752 ,  2363.99808054,   308.97273644,
        3200.99838291,  2976.98943476,  1152.98778075,   282.03948384,
        2910.95980196, 11163.96519029,  1317.95221218,  7087.0131035 ,
         435.04576514,   497.06129802,  2644.0534081 ,  4271.01610452,
      

In [73]:
#dataset['Date1']=dataset['Date1'].map(dt.datetime.toordinal)

In [74]:
#10 fold cv on test dataset
scores_test= cross_val_score(lir,X_test,y_test,cv=10)
scores_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [75]:
print(np.mean(scores_test))

0.9999999994952052


In [76]:
#date=dataset['Date1'] 
#date=np.array(date)
#date

#confirm=dataset['Daily new cases']
#confirm=np.array(confirm)
#confirm
#dataset['date']=np.array(date.reshape(-1,1))
#date
#dataset['confirm'] =np.array(confirm.reshape(-1,1))
#confirm

In [77]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [78]:
get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test)

0.005319148936170213

In [80]:
get_score(LinearRegression(), X_train, X_test, y_train, y_test)


0.9999999996691239

In [81]:
#date=np.array(date[737632,737633,737634,737636,737637,737432,737463,737492,737523,737553,737584,737614,737645,737676,737706,737737,737767,737650,737651,737652,737653,737654,737655,737656,737657,737658,737659,737660,737661,737662,737663,737664,737665,737666,737667,737668,737433,737464,737493,737524,737554,737585,737615,737646,737677,737707,737738,737768,737681,737682,737683,737684,737685,737686,737687,737688,737689,737690,737691,737692,737693,737694,737695,737696,737697,737698,737699,737434,737465,737494,737525,737555,737586,737616,737647,737678,737708])
#date.size

In [82]:
from sklearn.ensemble import RandomForestRegressor

In [84]:
get_score(RandomForestRegressor(n_estimators=40), X_train, X_test, y_train, y_test)

0.9994350510138713

In [85]:
#get_score(SVC(), X_train, X_test, y_train, y_test)

In [86]:
#from sklearn.model_selection import StratifiedKFold
#folds = StratifiedKFold(n_splits=3)

#scores_logistic = []
#scores_svm = []
#scores_rf = []
#scores_linear = []
#scores_rfr = []

#for train_index, test_index in folds.split(X,y):
#    X_train, X_test, y_train, y_test = X[train_index], y[test_index], \
                                       #X[train_index], y[test_index]
    #scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
   # scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
   # scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
   # scores_linear.append(get_score(LinearRegression(), X_train, X_test, y_train, y_test))
   # scores_rfr.append(get_score(RandomForestRegressor(n_estimators=40), X_train, X_test, y_train, y_test))

In [87]:
from sklearn.model_selection import cross_val_score

In [88]:
#cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X, y,cv=3)

In [89]:
#cross_val_score(SVC(gamma='auto'), X, y,cv=5)

In [90]:
#cross_val_score(RandomForestClassifier(n_estimators=40),X, y,cv=3)

In [95]:
cross_val_score(RandomForestRegressor(n_estimators=40),X, y,cv=3)

array([0.99946218, 0.99970642, 0.75780333])

In [96]:
 cross_val_score(LinearRegression(), X, y,cv=3)

array([1., 1., 1.])